# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')

setup(
    long_description=readme,
    long_description_content_type="text/markdown",
    name='fast-soup',
    version='1.2.0',
    description='BeautifulSoup interface for lxml',
    python_requires='==3.*,>=3.8.0',
    author='spumer',
    author_email='spumer-tm@yandex.ru',
    license='MIT',
    packages=['fast_soup'],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'beautifulsoup4==4.*,>=4.13.4', 'cssselect==1.*,>=1.3.0',
        'lxml>=5.4.0', 'html5-parser @ git+https://github.com/kkszysiu/html5-parser.git@0.4.13'
    ],
    extras_require={
        "dev": [
            "black>=19,<21", "bumpversion==0.*,>=0.5.3",
            "flake8-awesome==1.*,>=1.2.0", "pytest>=5,<7",
            "pytest-cov>=2,<5", "pytest-deadfixtures==2.*,>=2.1.0",
            "unify==0.*,>=0.5.0"
        ]
    },
)